/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gsbperso;

import java.awt.Graphics;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Loriane
 */
public class PanneauPhoto extends javax.swing.JPanel {

    /**
     * Creates new form PanneauPhoto
     */
    JFileChooser choixPhoto = null;
    ImageIcon lImage = null;

    public PanneauPhoto() {
        initComponents();
    }

    public void paintComponent(Graphics g) {
        super.paintComponent(g);
        if (this.choixPhoto != null) {
            if (lImage != null) {
                jLabelPhoto.getGraphics().drawImage(lImage.getImage(), 0, 0, null);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTitre = new javax.swing.JLabel();
        jButtonChoixIimage = new javax.swing.JButton();
        jLabelPhoto = new javax.swing.JLabel();

        jLabelTitre.setFont(new java.awt.Font("Sylfaen", 3, 24)); // NOI18N
        jLabelTitre.setText("Choisir une image");

        jButtonChoixIimage.setText("Choisir Photo");
        jButtonChoixIimage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonChoixIimageActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(260, 260, 260)
                        .addComponent(jLabelTitre, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(327, 327, 327)
                        .addComponent(jButtonChoixIimage))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(202, 202, 202)
                        .addComponent(jLabelPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(242, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabelTitre)
                .addGap(34, 34, 34)
                .addComponent(jLabelPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(jButtonChoixIimage)
                .addGap(88, 88, 88))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonChoixIimageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonChoixIimageActionPerformed
        if (choixPhoto == null) {
            choixPhoto = new JFileChooser(".");
            choixPhoto.setFileFilter(new FileNameExtensionFilter("Images", "png", "jpg"));
        }
        choixPhoto.setCurrentDirectory(choixPhoto.getCurrentDirectory());
        choixPhoto.showOpenDialog(null);
        if (choixPhoto.getSelectedFile() == null) {
            choixPhoto = null;
        } else {
            this.lImage = new ImageIcon(choixPhoto.getSelectedFile().toString());
        }
    }//GEN-LAST:event_jButtonChoixIimageActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonChoixIimage;
    private javax.swing.JLabel jLabelPhoto;
    private javax.swing.JLabel jLabelTitre;
    // End of variables declaration//GEN-END:variables
}
